/*
 * This file was automatically generated by EvoSuite
 * Thu Oct 19 21:46:04 GMT 2023
 */

package org.apache.commons.net.examples.ntp;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.net.examples.ntp.NTPClient;
import org.apache.commons.net.ntp.NtpV3Packet;
import org.apache.commons.net.ntp.TimeInfo;
import org.apache.commons.net.ntp.TimeStamp;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.System;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class NTPClient_ESTest extends NTPClient_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      // Undeclared exception!
      try { 
        NTPClient.main((String[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.examples.ntp.NTPClient", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      TimeStamp timeStamp0 = mock(TimeStamp.class, new ViolatedAssumptionAnswer());
      doReturn("253.51.180.166").when(timeStamp0).toDateString();
      doReturn("w],&cp5SH^\"R+~").when(timeStamp0).toString();
      TimeStamp timeStamp1 = mock(TimeStamp.class, new ViolatedAssumptionAnswer());
      doReturn("127.1270.0.0.3").when(timeStamp1).toDateString();
      doReturn("127.1270.0.0.3").when(timeStamp1).toString();
      TimeStamp timeStamp2 = mock(TimeStamp.class, new ViolatedAssumptionAnswer());
      doReturn("127.1270.0.0.3").when(timeStamp2).toDateString();
      doReturn("_l").when(timeStamp2).toString();
      TimeStamp timeStamp3 = mock(TimeStamp.class, new ViolatedAssumptionAnswer());
      doReturn("127.1270.0.0.3").when(timeStamp3).toDateString();
      doReturn("org.apache.commons.net.ntp.NtpUtils").when(timeStamp3).toString();
      NtpV3Packet ntpV3Packet0 = mock(NtpV3Packet.class, new ViolatedAssumptionAnswer());
      doReturn(3481).when(ntpV3Packet0).getLeapIndicator();
      doReturn(1).when(ntpV3Packet0).getMode();
      doReturn("w],&cp5SH^\"R+~").when(ntpV3Packet0).getModeName();
      doReturn(timeStamp1).when(ntpV3Packet0).getOriginateTimeStamp();
      doReturn(248).when(ntpV3Packet0).getPoll();
      doReturn(2278).when(ntpV3Packet0).getPrecision();
      doReturn(timeStamp2).when(ntpV3Packet0).getReceiveTimeStamp();
      doReturn(16, 2278).when(ntpV3Packet0).getReferenceId();
      doReturn(timeStamp0).when(ntpV3Packet0).getReferenceTimeStamp();
      doReturn((double)16).when(ntpV3Packet0).getRootDelayInMillisDouble();
      doReturn((double)2278).when(ntpV3Packet0).getRootDispersionInMillisDouble();
      doReturn(1).when(ntpV3Packet0).getStratum();
      doReturn(timeStamp3).when(ntpV3Packet0).getTransmitTimeStamp();
      doReturn(3481).when(ntpV3Packet0).getVersion();
      Long long0 = new Long((-2374L));
      TimeInfo timeInfo0 = mock(TimeInfo.class, new ViolatedAssumptionAnswer());
      doReturn(long0).when(timeInfo0).getDelay();
      doReturn(ntpV3Packet0).when(timeInfo0).getMessage();
      doReturn(long0).when(timeInfo0).getOffset();
      doReturn(1885L).when(timeInfo0).getReturnTime();
      NTPClient.processResponse(timeInfo0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      TimeStamp timeStamp0 = mock(TimeStamp.class, new ViolatedAssumptionAnswer());
      doReturn("253.51.180.166").when(timeStamp0).toDateString();
      doReturn("255.255.242.112").when(timeStamp0).toString();
      TimeStamp timeStamp1 = mock(TimeStamp.class, new ViolatedAssumptionAnswer());
      doReturn("127.1270.0.0.3").when(timeStamp1).toDateString();
      doReturn("127.1270.0.0.3").when(timeStamp1).toString();
      TimeStamp timeStamp2 = mock(TimeStamp.class, new ViolatedAssumptionAnswer());
      doReturn("bqVnjGBlL^ZnC6KRs").when(timeStamp2).toDateString();
      doReturn("_l").when(timeStamp2).toString();
      TimeStamp timeStamp3 = mock(TimeStamp.class, new ViolatedAssumptionAnswer());
      doReturn("EEE, MMM dd yyyy HH:mm:ss.SSS").when(timeStamp3).toDateString();
      doReturn("0.0.15.205").when(timeStamp3).toString();
      NtpV3Packet ntpV3Packet0 = mock(NtpV3Packet.class, new ViolatedAssumptionAnswer());
      doReturn(3481).when(ntpV3Packet0).getLeapIndicator();
      doReturn(0).when(ntpV3Packet0).getMode();
      doReturn("255.255.242.112").when(ntpV3Packet0).getModeName();
      doReturn(timeStamp1).when(ntpV3Packet0).getOriginateTimeStamp();
      doReturn(248).when(ntpV3Packet0).getPoll();
      doReturn(2278).when(ntpV3Packet0).getPrecision();
      doReturn(timeStamp2).when(ntpV3Packet0).getReceiveTimeStamp();
      doReturn(16, 0).when(ntpV3Packet0).getReferenceId();
      doReturn(timeStamp0).when(ntpV3Packet0).getReferenceTimeStamp();
      doReturn((double)16).when(ntpV3Packet0).getRootDelayInMillisDouble();
      doReturn(0.0).when(ntpV3Packet0).getRootDispersionInMillisDouble();
      doReturn(0).when(ntpV3Packet0).getStratum();
      doReturn(timeStamp3).when(ntpV3Packet0).getTransmitTimeStamp();
      doReturn(3481).when(ntpV3Packet0).getVersion();
      TimeInfo timeInfo0 = mock(TimeInfo.class, new ViolatedAssumptionAnswer());
      doReturn((Long) null).when(timeInfo0).getDelay();
      doReturn(ntpV3Packet0).when(timeInfo0).getMessage();
      doReturn((Long) null).when(timeInfo0).getOffset();
      doReturn(1885L).when(timeInfo0).getReturnTime();
      NTPClient.processResponse(timeInfo0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      TimeStamp timeStamp0 = mock(TimeStamp.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(timeStamp0).toDateString();
      doReturn((String) null).when(timeStamp0).toString();
      NtpV3Packet ntpV3Packet0 = mock(NtpV3Packet.class, new ViolatedAssumptionAnswer());
      doReturn(41).when(ntpV3Packet0).getLeapIndicator();
      doReturn((-1091)).when(ntpV3Packet0).getMode();
      doReturn("HD[bI_~z").when(ntpV3Packet0).getModeName();
      doReturn((TimeStamp) null).when(ntpV3Packet0).getOriginateTimeStamp();
      doReturn(41).when(ntpV3Packet0).getPoll();
      doReturn((-3472)).when(ntpV3Packet0).getPrecision();
      doReturn(41).when(ntpV3Packet0).getReferenceId();
      doReturn(timeStamp0).when(ntpV3Packet0).getReferenceTimeStamp();
      doReturn((double)(-1091)).when(ntpV3Packet0).getRootDelayInMillisDouble();
      doReturn((double)41).when(ntpV3Packet0).getRootDispersionInMillisDouble();
      doReturn((-3472)).when(ntpV3Packet0).getStratum();
      doReturn((-3472)).when(ntpV3Packet0).getVersion();
      TimeInfo timeInfo0 = mock(TimeInfo.class, new ViolatedAssumptionAnswer());
      doReturn(ntpV3Packet0).when(timeInfo0).getMessage();
      // Undeclared exception!
      try { 
        NTPClient.processResponse(timeInfo0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.examples.ntp.NTPClient", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      NtpV3Packet ntpV3Packet0 = mock(NtpV3Packet.class, new ViolatedAssumptionAnswer());
      doReturn(0).when(ntpV3Packet0).getLeapIndicator();
      doReturn(0).when(ntpV3Packet0).getMode();
      doReturn((String) null).when(ntpV3Packet0).getModeName();
      doReturn(0).when(ntpV3Packet0).getPoll();
      doReturn(0).when(ntpV3Packet0).getPrecision();
      doReturn(0).when(ntpV3Packet0).getReferenceId();
      doReturn((TimeStamp) null).when(ntpV3Packet0).getReferenceTimeStamp();
      doReturn(0.0).when(ntpV3Packet0).getRootDelayInMillisDouble();
      doReturn(0.0).when(ntpV3Packet0).getRootDispersionInMillisDouble();
      doReturn(0).when(ntpV3Packet0).getStratum();
      doReturn(0).when(ntpV3Packet0).getVersion();
      TimeInfo timeInfo0 = mock(TimeInfo.class, new ViolatedAssumptionAnswer());
      doReturn(ntpV3Packet0).when(timeInfo0).getMessage();
      // Undeclared exception!
      try { 
        NTPClient.processResponse(timeInfo0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.examples.ntp.NTPClient", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      TimeStamp timeStamp0 = mock(TimeStamp.class, new ViolatedAssumptionAnswer());
      doReturn("0.0.12.193").when(timeStamp0).toDateString();
      doReturn(", precision=").when(timeStamp0).toString();
      TimeStamp timeStamp1 = mock(TimeStamp.class, new ViolatedAssumptionAnswer());
      doReturn("").when(timeStamp1).toDateString();
      doReturn("  ").when(timeStamp1).toString();
      TimeStamp timeStamp2 = mock(TimeStamp.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(timeStamp2).toDateString();
      doReturn((String) null).when(timeStamp2).toString();
      NtpV3Packet ntpV3Packet0 = mock(NtpV3Packet.class, new ViolatedAssumptionAnswer());
      doReturn(1446).when(ntpV3Packet0).getLeapIndicator();
      doReturn(1446).when(ntpV3Packet0).getMode();
      doReturn("  ").when(ntpV3Packet0).getModeName();
      doReturn(timeStamp1).when(ntpV3Packet0).getOriginateTimeStamp();
      doReturn(1446).when(ntpV3Packet0).getPoll();
      doReturn((-1377)).when(ntpV3Packet0).getPrecision();
      doReturn(timeStamp2).when(ntpV3Packet0).getReceiveTimeStamp();
      doReturn(653).when(ntpV3Packet0).getReferenceId();
      doReturn(timeStamp0).when(ntpV3Packet0).getReferenceTimeStamp();
      doReturn((double)653).when(ntpV3Packet0).getRootDelayInMillisDouble();
      doReturn((double)(-1377)).when(ntpV3Packet0).getRootDispersionInMillisDouble();
      doReturn(15).when(ntpV3Packet0).getStratum();
      doReturn((TimeStamp) null).when(ntpV3Packet0).getTransmitTimeStamp();
      doReturn(653).when(ntpV3Packet0).getVersion();
      TimeInfo timeInfo0 = mock(TimeInfo.class, new ViolatedAssumptionAnswer());
      doReturn(ntpV3Packet0).when(timeInfo0).getMessage();
      doReturn((long)1446).when(timeInfo0).getReturnTime();
      // Undeclared exception!
      try { 
        NTPClient.processResponse(timeInfo0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.examples.ntp.NTPClient", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      TimeStamp timeStamp0 = mock(TimeStamp.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(timeStamp0).toDateString();
      doReturn((String) null).when(timeStamp0).toString();
      NtpV3Packet ntpV3Packet0 = mock(NtpV3Packet.class, new ViolatedAssumptionAnswer());
      doReturn(199).when(ntpV3Packet0).getLeapIndicator();
      doReturn(199).when(ntpV3Packet0).getMode();
      doReturn("N/A").when(ntpV3Packet0).getModeName();
      doReturn((TimeStamp) null).when(ntpV3Packet0).getOriginateTimeStamp();
      doReturn((-1)).when(ntpV3Packet0).getPoll();
      doReturn((-1)).when(ntpV3Packet0).getPrecision();
      doReturn((-1)).when(ntpV3Packet0).getReferenceId();
      doReturn(timeStamp0).when(ntpV3Packet0).getReferenceTimeStamp();
      doReturn((double)(-1)).when(ntpV3Packet0).getRootDelayInMillisDouble();
      doReturn((double)199).when(ntpV3Packet0).getRootDispersionInMillisDouble();
      doReturn((-603)).when(ntpV3Packet0).getStratum();
      doReturn(199).when(ntpV3Packet0).getVersion();
      TimeInfo timeInfo0 = mock(TimeInfo.class, new ViolatedAssumptionAnswer());
      doReturn(ntpV3Packet0).when(timeInfo0).getMessage();
      // Undeclared exception!
      try { 
        NTPClient.processResponse(timeInfo0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.examples.ntp.NTPClient", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      TimeStamp timeStamp0 = mock(TimeStamp.class, new ViolatedAssumptionAnswer());
      doReturn(", precision=").when(timeStamp0).toDateString();
      doReturn("Control").when(timeStamp0).toString();
      TimeStamp timeStamp1 = mock(TimeStamp.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(timeStamp1).toDateString();
      doReturn((String) null).when(timeStamp1).toString();
      NtpV3Packet ntpV3Packet0 = mock(NtpV3Packet.class, new ViolatedAssumptionAnswer());
      doReturn(3481).when(ntpV3Packet0).getLeapIndicator();
      doReturn(1).when(ntpV3Packet0).getMode();
      doReturn("w],&cp5SH^\"R+~").when(ntpV3Packet0).getModeName();
      doReturn(timeStamp1).when(ntpV3Packet0).getOriginateTimeStamp();
      doReturn(248).when(ntpV3Packet0).getPoll();
      doReturn(2278).when(ntpV3Packet0).getPrecision();
      doReturn((TimeStamp) null).when(ntpV3Packet0).getReceiveTimeStamp();
      doReturn(16, (-426)).when(ntpV3Packet0).getReferenceId();
      doReturn(timeStamp0).when(ntpV3Packet0).getReferenceTimeStamp();
      doReturn((double)16).when(ntpV3Packet0).getRootDelayInMillisDouble();
      doReturn(0.0).when(ntpV3Packet0).getRootDispersionInMillisDouble();
      doReturn(1).when(ntpV3Packet0).getStratum();
      doReturn(3481).when(ntpV3Packet0).getVersion();
      TimeInfo timeInfo0 = mock(TimeInfo.class, new ViolatedAssumptionAnswer());
      doReturn(ntpV3Packet0).when(timeInfo0).getMessage();
      doReturn(0L).when(timeInfo0).getReturnTime();
      // Undeclared exception!
      try { 
        NTPClient.processResponse(timeInfo0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.examples.ntp.NTPClient", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      String[] stringArray0 = new String[0];
      // Undeclared exception!
      try { 
        NTPClient.main(stringArray0);
        fail("Expecting exception: System.SystemExitException");
      
      } catch(System.SystemExitException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.System", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      String[] stringArray0 = new String[1];
      NTPClient.main(stringArray0);
      assertEquals(1, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      NTPClient nTPClient0 = new NTPClient();
  }
}
