/*
 * This file was automatically generated by EvoSuite
 * Thu Oct 19 21:50:43 GMT 2023
 */

package org.apache.commons.net.bsd;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.net.bsd.RExecClient;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RExecClient_ESTest extends RExecClient_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      RExecClient rExecClient0 = new RExecClient();
      // Undeclared exception!
      try { 
        rExecClient0.rexec("", "", "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.bsd.RExecClient", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      RExecClient rExecClient0 = new RExecClient();
      // Undeclared exception!
      try { 
        rExecClient0.rexec("U|yL&>!", "", "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.bsd.RExecClient", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      RExecClient rExecClient0 = new RExecClient();
      rExecClient0.setRemoteVerificationEnabled(true);
      boolean boolean0 = rExecClient0.isRemoteVerificationEnabled();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      RExecClient rExecClient0 = new RExecClient();
      // Undeclared exception!
      try { 
        rExecClient0.createErrorStream();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.SocketClient", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      RExecClient rExecClient0 = new RExecClient();
      // Undeclared exception!
      try { 
        rExecClient0.rexec("\r\n", "\r\n", "\r\n", false);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.bsd.RExecClient", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      RExecClient rExecClient0 = new RExecClient();
      // Undeclared exception!
      try { 
        rExecClient0.rexec("\r\n", "\r\n", "\r\n", true);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.SocketClient", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      RExecClient rExecClient0 = new RExecClient();
      rExecClient0.disconnect();
      assertEquals(512, rExecClient0.getDefaultPort());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      RExecClient rExecClient0 = new RExecClient();
      rExecClient0.isRemoteVerificationEnabled();
      assertEquals(512, rExecClient0.getDefaultPort());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      RExecClient rExecClient0 = new RExecClient();
      rExecClient0.getErrorStream();
      assertEquals(512, rExecClient0.getDefaultPort());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      RExecClient rExecClient0 = new RExecClient();
      rExecClient0.getOutputStream();
      assertEquals(512, rExecClient0.getDefaultPort());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      RExecClient rExecClient0 = new RExecClient();
      rExecClient0.getInputStream();
      assertEquals(512, rExecClient0.getDefaultPort());
  }
}
