/*
 * This file was automatically generated by EvoSuite
 * Thu Oct 19 23:47:48 GMT 2023
 */

package org.apache.commons.net.nntp;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.net.nntp.NNTP;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class NNTP_ESTest extends NNTP_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      NNTP nNTP0 = new NNTP();
      // Undeclared exception!
      try { 
        nNTP0.xhdr("0.M|/WP)?X0oVA!X", "*Q<fa[30||+^9AO");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.nntp.NNTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      NNTP nNTP0 = new NNTP();
      // Undeclared exception!
      try { 
        nNTP0.newnews((String) null, "", (String) null, true, "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.nntp.NNTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      NNTP nNTP0 = new NNTP();
      // Undeclared exception!
      try { 
        nNTP0.newgroups(",&3WfNI2WX", "=<8", true, ",&3WfNI2WX");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.nntp.NNTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      NNTP nNTP0 = new NNTP();
      nNTP0.getCommandSupport();
      assertFalse(nNTP0.isAllowedToPost());
      assertEquals(119, nNTP0.getDefaultPort());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      NNTP nNTP0 = new NNTP();
      // Undeclared exception!
      try { 
        nNTP0.sendCommand((-1290), (String) null);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -1290
         //
         verifyException("org.apache.commons.net.nntp.NNTPCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      NNTP nNTP0 = new NNTP();
      // Undeclared exception!
      try { 
        nNTP0.sendCommand(0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.nntp.NNTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      NNTP nNTP0 = new NNTP();
      // Undeclared exception!
      try { 
        nNTP0.getReply();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.nntp.NNTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      NNTP nNTP0 = new NNTP();
      // Undeclared exception!
      try { 
        nNTP0._connectAction_();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.SocketClient", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      NNTP nNTP0 = new NNTP();
      // Undeclared exception!
      try { 
        nNTP0.sendCommand("ACTIVE ", "ACTIVE ");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.nntp.NNTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      NNTP nNTP0 = new NNTP();
      // Undeclared exception!
      try { 
        nNTP0.sendCommand(0, "W|e");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.nntp.NNTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      NNTP nNTP0 = new NNTP();
      // Undeclared exception!
      try { 
        nNTP0.sendCommand(1909);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 1909
         //
         verifyException("org.apache.commons.net.nntp.NNTPCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      NNTP nNTP0 = new NNTP();
      // Undeclared exception!
      try { 
        nNTP0.article((long) 0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.nntp.NNTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      NNTP nNTP0 = new NNTP();
      // Undeclared exception!
      try { 
        nNTP0.newnews((String) null, (String) null, (String) null, false, (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.nntp.NNTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      NNTP nNTP0 = new NNTP();
      // Undeclared exception!
      try { 
        nNTP0.newnews("", "", "B.", true, "B.");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.nntp.NNTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      NNTP nNTP0 = new NNTP();
      // Undeclared exception!
      try { 
        nNTP0.newgroups("^JRME8O[kb-#d:z\"", "^JRME8O[kb-#d:z\"", true, (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.nntp.NNTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      NNTP nNTP0 = new NNTP();
      // Undeclared exception!
      try { 
        nNTP0.newgroups("Ycw?Lm/mc%bk4S}BP", "", true, "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.nntp.NNTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      NNTP nNTP0 = new NNTP();
      // Undeclared exception!
      try { 
        nNTP0.newgroups("4AlpIG", "LST", false, "LST");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.nntp.NNTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      NNTP nNTP0 = new NNTP();
      // Undeclared exception!
      try { 
        nNTP0.stat();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.nntp.NNTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      NNTP nNTP0 = new NNTP();
      // Undeclared exception!
      try { 
        nNTP0.quit();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.nntp.NNTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      NNTP nNTP0 = new NNTP();
      // Undeclared exception!
      try { 
        nNTP0.head((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.nntp.NNTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      NNTP nNTP0 = new NNTP();
      // Undeclared exception!
      try { 
        nNTP0.sendCommand("qh=R)@?N%m]bvygT_");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.nntp.NNTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      NNTP nNTP0 = new NNTP();
      // Undeclared exception!
      try { 
        nNTP0.authinfoUser("EZV_;RK7yW^?5XuRND");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.nntp.NNTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      NNTP nNTP0 = new NNTP();
      // Undeclared exception!
      try { 
        nNTP0.last();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.nntp.NNTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      NNTP nNTP0 = new NNTP();
      // Undeclared exception!
      try { 
        nNTP0.ihave((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.nntp.NNTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      NNTP nNTP0 = new NNTP();
      // Undeclared exception!
      try { 
        nNTP0.body((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.nntp.NNTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      NNTP nNTP0 = new NNTP();
      boolean boolean0 = nNTP0.isAllowedToPost();
      assertFalse(boolean0);
      assertEquals(119, nNTP0.getDefaultPort());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      NNTP nNTP0 = new NNTP();
      // Undeclared exception!
      try { 
        nNTP0.help();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.nntp.NNTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      NNTP nNTP0 = new NNTP();
      // Undeclared exception!
      try { 
        nNTP0.stat("yVcY0yo{0_)");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.nntp.NNTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      NNTP nNTP0 = new NNTP();
      // Undeclared exception!
      try { 
        nNTP0.next();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.nntp.NNTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      NNTP nNTP0 = new NNTP();
      // Undeclared exception!
      try { 
        nNTP0.article("Ws;");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.nntp.NNTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      NNTP nNTP0 = new NNTP();
      // Undeclared exception!
      try { 
        nNTP0.body();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.nntp.NNTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      NNTP nNTP0 = new NNTP();
      String string0 = nNTP0.getReplyString();
      assertEquals(119, nNTP0.getDefaultPort());
      assertNull(string0);
      assertFalse(nNTP0.isAllowedToPost());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      NNTP nNTP0 = new NNTP();
      // Undeclared exception!
      try { 
        nNTP0.group("");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.nntp.NNTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      NNTP nNTP0 = new NNTP();
      // Undeclared exception!
      try { 
        nNTP0.listActive("O!8G<y^$'.yZ>2g_dYq");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.nntp.NNTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      NNTP nNTP0 = new NNTP();
      // Undeclared exception!
      try { 
        nNTP0.stat(156);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.nntp.NNTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      NNTP nNTP0 = new NNTP();
      // Undeclared exception!
      try { 
        nNTP0.stat((-1713L));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.nntp.NNTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      NNTP nNTP0 = new NNTP();
      // Undeclared exception!
      try { 
        nNTP0.article();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.nntp.NNTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      NNTP nNTP0 = new NNTP();
      // Undeclared exception!
      try { 
        nNTP0.list();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.nntp.NNTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      NNTP nNTP0 = new NNTP();
      // Undeclared exception!
      try { 
        nNTP0.head(11);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.nntp.NNTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      NNTP nNTP0 = new NNTP();
      // Undeclared exception!
      try { 
        nNTP0.head((-3071L));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.nntp.NNTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      NNTP nNTP0 = new NNTP();
      int int0 = nNTP0.getReplyCode();
      assertEquals(119, nNTP0.getDefaultPort());
      assertEquals(0, int0);
      assertFalse(nNTP0.isAllowedToPost());
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      NNTP nNTP0 = new NNTP();
      // Undeclared exception!
      try { 
        nNTP0.article(86);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.nntp.NNTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      NNTP nNTP0 = new NNTP();
      // Undeclared exception!
      try { 
        nNTP0.xover("org.apache.commons.net.nntp.NNTP");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.nntp.NNTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      NNTP nNTP0 = new NNTP();
      // Undeclared exception!
      try { 
        nNTP0.authinfoPass("org.apache.commons.net.nntp.NNTPCommand");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.nntp.NNTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      NNTP nNTP0 = new NNTP();
      // Undeclared exception!
      try { 
        nNTP0.head();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.nntp.NNTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      NNTP nNTP0 = new NNTP();
      // Undeclared exception!
      try { 
        nNTP0.post();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.nntp.NNTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      NNTP nNTP0 = new NNTP();
      nNTP0.disconnect();
      assertFalse(nNTP0.isAllowedToPost());
      assertEquals(119, nNTP0.getDefaultPort());
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      NNTP nNTP0 = new NNTP();
      // Undeclared exception!
      try { 
        nNTP0.body(0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.nntp.NNTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      NNTP nNTP0 = new NNTP();
      // Undeclared exception!
      try { 
        nNTP0.body((-2135L));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.nntp.NNTP", e);
      }
  }
}
