/*
 * This file was automatically generated by EvoSuite
 * Thu Oct 19 21:57:24 GMT 2023
 */

package org.apache.commons.net.smtp;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import javax.net.ssl.SSLContext;
import org.apache.commons.net.smtp.AuthenticatingSMTPClient;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AuthenticatingSMTPClient_ESTest extends AuthenticatingSMTPClient_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      AuthenticatingSMTPClient authenticatingSMTPClient0 = new AuthenticatingSMTPClient(" m6Oofj", " m6Oofj");
      // Undeclared exception!
      try { 
        authenticatingSMTPClient0.elogin();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.SocketClient", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      AuthenticatingSMTPClient.AUTH_METHOD authenticatingSMTPClient_AUTH_METHOD0 = AuthenticatingSMTPClient.AUTH_METHOD.LOGIN;
      String string0 = AuthenticatingSMTPClient.AUTH_METHOD.getAuthName(authenticatingSMTPClient_AUTH_METHOD0);
      assertNotNull(string0);
      assertEquals("LOGIN", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      AuthenticatingSMTPClient.AUTH_METHOD authenticatingSMTPClient_AUTH_METHOD0 = AuthenticatingSMTPClient.AUTH_METHOD.XOAUTH;
      String string0 = AuthenticatingSMTPClient.AUTH_METHOD.getAuthName(authenticatingSMTPClient_AUTH_METHOD0);
      assertNotNull(string0);
      assertEquals("XOAUTH", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      AuthenticatingSMTPClient.AUTH_METHOD authenticatingSMTPClient_AUTH_METHOD0 = AuthenticatingSMTPClient.AUTH_METHOD.XOAUTH2;
      String string0 = AuthenticatingSMTPClient.AUTH_METHOD.getAuthName(authenticatingSMTPClient_AUTH_METHOD0);
      assertEquals("XOAUTH2", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      AuthenticatingSMTPClient.AUTH_METHOD authenticatingSMTPClient_AUTH_METHOD0 = AuthenticatingSMTPClient.AUTH_METHOD.CRAM_MD5;
      String string0 = AuthenticatingSMTPClient.AUTH_METHOD.getAuthName(authenticatingSMTPClient_AUTH_METHOD0);
      assertNotNull(string0);
      assertEquals("CRAM-MD5", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      AuthenticatingSMTPClient.AUTH_METHOD authenticatingSMTPClient_AUTH_METHOD0 = AuthenticatingSMTPClient.AUTH_METHOD.PLAIN;
      String string0 = AuthenticatingSMTPClient.AUTH_METHOD.getAuthName(authenticatingSMTPClient_AUTH_METHOD0);
      assertNotNull(string0);
      assertEquals("PLAIN", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      AuthenticatingSMTPClient authenticatingSMTPClient0 = new AuthenticatingSMTPClient("", true);
      AuthenticatingSMTPClient.AUTH_METHOD authenticatingSMTPClient_AUTH_METHOD0 = AuthenticatingSMTPClient.AUTH_METHOD.LOGIN;
      // Undeclared exception!
      try { 
        authenticatingSMTPClient0.auth(authenticatingSMTPClient_AUTH_METHOD0, "", "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.smtp.SMTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      AuthenticatingSMTPClient authenticatingSMTPClient0 = new AuthenticatingSMTPClient("N");
      assertEquals(60000, authenticatingSMTPClient0.getConnectTimeout());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      SSLContext sSLContext0 = mock(SSLContext.class, new ViolatedAssumptionAnswer());
      AuthenticatingSMTPClient authenticatingSMTPClient0 = new AuthenticatingSMTPClient(true, sSLContext0);
      // Undeclared exception!
      try { 
        authenticatingSMTPClient0.elogin("\r\n");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.smtp.SMTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      AuthenticatingSMTPClient authenticatingSMTPClient0 = new AuthenticatingSMTPClient();
      // Undeclared exception!
      try { 
        authenticatingSMTPClient0.ehlo("");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.smtp.SMTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      AuthenticatingSMTPClient authenticatingSMTPClient0 = new AuthenticatingSMTPClient("", false, "^T\"XPQ");
      // Undeclared exception!
      try { 
        authenticatingSMTPClient0.getEnhancedReplyCode();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.smtp.AuthenticatingSMTPClient", e);
      }
  }
}
