/*
 * This file was automatically generated by EvoSuite
 * Thu Oct 19 21:37:59 GMT 2023
 */

package org.apache.commons.net.io;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.OutputStream;
import org.apache.commons.net.io.FromNetASCIIOutputStream;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FromNetASCIIOutputStream_ESTest extends FromNetASCIIOutputStream_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      OutputStream outputStream0 = mock(OutputStream.class, new ViolatedAssumptionAnswer());
      FromNetASCIIOutputStream fromNetASCIIOutputStream0 = new FromNetASCIIOutputStream(outputStream0);
      fromNetASCIIOutputStream0.write((byte[]) null, (-528), (-528));
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      FromNetASCIIOutputStream fromNetASCIIOutputStream0 = new FromNetASCIIOutputStream((OutputStream) null);
      byte[] byteArray0 = new byte[3];
      // Undeclared exception!
      try { 
        fromNetASCIIOutputStream0.write(byteArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.io.FromNetASCIIOutputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      FromNetASCIIOutputStream fromNetASCIIOutputStream0 = new FromNetASCIIOutputStream((OutputStream) null);
      // Undeclared exception!
      try { 
        fromNetASCIIOutputStream0.write((-1));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.io.FromNetASCIIOutputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      FromNetASCIIOutputStream fromNetASCIIOutputStream0 = new FromNetASCIIOutputStream((OutputStream) null);
      // Undeclared exception!
      try { 
        fromNetASCIIOutputStream0.close();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      OutputStream outputStream0 = mock(OutputStream.class, new ViolatedAssumptionAnswer());
      FromNetASCIIOutputStream fromNetASCIIOutputStream0 = new FromNetASCIIOutputStream(outputStream0);
      fromNetASCIIOutputStream0.write((int) (byte) (-110));
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      OutputStream outputStream0 = mock(OutputStream.class, new ViolatedAssumptionAnswer());
      FromNetASCIIOutputStream fromNetASCIIOutputStream0 = new FromNetASCIIOutputStream(outputStream0);
      fromNetASCIIOutputStream0.close();
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      OutputStream outputStream0 = mock(OutputStream.class, new ViolatedAssumptionAnswer());
      FromNetASCIIOutputStream fromNetASCIIOutputStream0 = new FromNetASCIIOutputStream(outputStream0);
      byte[] byteArray0 = new byte[8];
      fromNetASCIIOutputStream0.write(byteArray0);
      assertArrayEquals(new byte[] {(byte)0, (byte)0, (byte)0, (byte)0, (byte)0, (byte)0, (byte)0, (byte)0}, byteArray0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      FromNetASCIIOutputStream fromNetASCIIOutputStream0 = new FromNetASCIIOutputStream((OutputStream) null);
      // Undeclared exception!
      try { 
        fromNetASCIIOutputStream0.write((byte[]) null, 10, 865);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.io.FromNetASCIIOutputStream", e);
      }
  }
}
