/*
 * This file was automatically generated by EvoSuite
 * Thu Oct 19 21:58:09 GMT 2023
 */

package org.apache.commons.net.ftp;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.net.ftp.NoProtocolSslConfigurationProxy;
import org.apache.ftpserver.ssl.SslConfiguration;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class NoProtocolSslConfigurationProxy_ESTest extends NoProtocolSslConfigurationProxy_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      NoProtocolSslConfigurationProxy noProtocolSslConfigurationProxy0 = new NoProtocolSslConfigurationProxy((SslConfiguration) null);
      // Undeclared exception!
      try { 
        noProtocolSslConfigurationProxy0.getSSLContext("org.apache.commons.net.ftp.NoProtocolSslConfigurationProxy");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.ftp.NoProtocolSslConfigurationProxy", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      NoProtocolSslConfigurationProxy noProtocolSslConfigurationProxy0 = new NoProtocolSslConfigurationProxy((SslConfiguration) null);
      String[] stringArray0 = noProtocolSslConfigurationProxy0.getEnabledProtocols();
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      NoProtocolSslConfigurationProxy noProtocolSslConfigurationProxy0 = new NoProtocolSslConfigurationProxy((SslConfiguration) null);
      // Undeclared exception!
      try { 
        noProtocolSslConfigurationProxy0.getEnabledCipherSuites();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.ftp.NoProtocolSslConfigurationProxy", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      NoProtocolSslConfigurationProxy noProtocolSslConfigurationProxy0 = new NoProtocolSslConfigurationProxy((SslConfiguration) null);
      // Undeclared exception!
      try { 
        noProtocolSslConfigurationProxy0.getSocketFactory();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.ftp.NoProtocolSslConfigurationProxy", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      NoProtocolSslConfigurationProxy noProtocolSslConfigurationProxy0 = new NoProtocolSslConfigurationProxy((SslConfiguration) null);
      // Undeclared exception!
      try { 
        noProtocolSslConfigurationProxy0.getClientAuth();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.ftp.NoProtocolSslConfigurationProxy", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      NoProtocolSslConfigurationProxy noProtocolSslConfigurationProxy0 = new NoProtocolSslConfigurationProxy((SslConfiguration) null);
      // Undeclared exception!
      try { 
        noProtocolSslConfigurationProxy0.getSSLContext();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.ftp.NoProtocolSslConfigurationProxy", e);
      }
  }
}
