/*
 * This file was automatically generated by EvoSuite
 * Thu Oct 19 23:01:09 GMT 2023
 */

package org.apache.commons.net.ftp.parser;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.net.ftp.FTPFile;
import org.apache.commons.net.ftp.FTPFileEntryParser;
import org.apache.commons.net.ftp.parser.CompositeFileEntryParser;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CompositeFileEntryParser_ESTest extends CompositeFileEntryParser_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FTPFileEntryParser[] fTPFileEntryParserArray0 = new FTPFileEntryParser[1];
      FTPFileEntryParser fTPFileEntryParser0 = mock(FTPFileEntryParser.class, new ViolatedAssumptionAnswer());
      doReturn((FTPFile) null).when(fTPFileEntryParser0).parseFTPEntry(anyString());
      fTPFileEntryParserArray0[0] = fTPFileEntryParser0;
      CompositeFileEntryParser compositeFileEntryParser0 = new CompositeFileEntryParser(fTPFileEntryParserArray0);
      FTPFile fTPFile0 = compositeFileEntryParser0.parseFTPEntry("Name");
      assertNull(fTPFile0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CompositeFileEntryParser compositeFileEntryParser0 = new CompositeFileEntryParser((FTPFileEntryParser[]) null);
      // Undeclared exception!
      try { 
        compositeFileEntryParser0.parseFTPEntry("");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.ftp.parser.CompositeFileEntryParser", e);
      }
  }
}
