/*
 * This file was automatically generated by EvoSuite
 * Thu Oct 19 22:52:46 GMT 2023
 */

package org.apache.commons.net.ftp.parser;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.net.ftp.FTPClientConfig;
import org.apache.commons.net.ftp.FTPFile;
import org.apache.commons.net.ftp.parser.NTFTPEntryParser;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class NTFTPEntryParser_ESTest extends NTFTPEntryParser_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      NTFTPEntryParser nTFTPEntryParser0 = new NTFTPEntryParser((FTPClientConfig) null);
      assertEquals(0, nTFTPEntryParser0.getGroupCnt());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      NTFTPEntryParser nTFTPEntryParser0 = new NTFTPEntryParser();
      // Undeclared exception!
      try { 
        nTFTPEntryParser0.parseFTPEntry((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      NTFTPEntryParser nTFTPEntryParser0 = new NTFTPEntryParser();
      nTFTPEntryParser0.setRegex("");
      // Undeclared exception!
      try { 
        nTFTPEntryParser0.parseFTPEntry("");
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // No group 1
         //
         verifyException("java.util.regex.Matcher", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      FTPClientConfig fTPClientConfig0 = mock(FTPClientConfig.class, new ViolatedAssumptionAnswer());
      doReturn((String) null, (String) null).when(fTPClientConfig0).getDefaultDateFormatStr();
      doReturn((String) null, (String) null).when(fTPClientConfig0).getRecentDateFormatStr();
      doReturn((String) null).when(fTPClientConfig0).getServerLanguageCode();
      doReturn((String) null).when(fTPClientConfig0).getShortMonthNames();
      NTFTPEntryParser nTFTPEntryParser0 = null;
      try {
        nTFTPEntryParser0 = new NTFTPEntryParser(fTPClientConfig0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // defaultFormatString cannot be null
         //
         verifyException("org.apache.commons.net.ftp.parser.FTPTimestampParserImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      NTFTPEntryParser nTFTPEntryParser0 = new NTFTPEntryParser();
      FTPClientConfig fTPClientConfig0 = nTFTPEntryParser0.getDefaultConfiguration();
      assertEquals("MM-dd-yy hh:mma", fTPClientConfig0.getDefaultDateFormatStr());
      assertEquals("WINDOWS", fTPClientConfig0.getServerSystemKey());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      NTFTPEntryParser nTFTPEntryParser0 = new NTFTPEntryParser();
      FTPFile fTPFile0 = nTFTPEntryParser0.parseFTPEntry("FTP response 421 eceive|.  ere Iosedconncti");
      assertNotNull(fTPFile0);
      assertEquals("eceive|.  ere Iosedconncti", fTPFile0.getName());
      assertEquals(421L, fTPFile0.getSize());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      NTFTPEntryParser nTFTPEntryParser0 = new NTFTPEntryParser();
      FTPFile fTPFile0 = nTFTPEntryParser0.parseFTPEntry("O6Ax");
      assertNull(fTPFile0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      FTPClientConfig fTPClientConfig0 = mock(FTPClientConfig.class, new ViolatedAssumptionAnswer());
      doReturn("", ";/gKS").when(fTPClientConfig0).getDefaultDateFormatStr();
      doReturn((String) null, "1&").when(fTPClientConfig0).getRecentDateFormatStr();
      doReturn((String) null).when(fTPClientConfig0).getServerLanguageCode();
      doReturn((String) null).when(fTPClientConfig0).getShortMonthNames();
      NTFTPEntryParser nTFTPEntryParser0 = null;
      try {
        nTFTPEntryParser0 = new NTFTPEntryParser(fTPClientConfig0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Illegal pattern character 'g'
         //
         verifyException("java.text.SimpleDateFormat", e);
      }
  }
}
