/*
 * This file was automatically generated by EvoSuite
 * Thu Oct 19 22:54:21 GMT 2023
 */

package org.apache.commons.net.telnet;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.commons.net.telnet.InvalidTelnetOptionException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class InvalidTelnetOptionException_ESTest extends InvalidTelnetOptionException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      InvalidTelnetOptionException invalidTelnetOptionException0 = new InvalidTelnetOptionException("", (-68));
      String string0 = invalidTelnetOptionException0.getMessage();
      assertEquals(": -68", string0);
  }
}
