/*
 * This file was automatically generated by EvoSuite
 * Thu Oct 19 21:55:49 GMT 2023
 */

package org.apache.commons.net.telnet;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.commons.net.telnet.SimpleOptionHandler;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SimpleOptionHandler_ESTest extends SimpleOptionHandler_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SimpleOptionHandler simpleOptionHandler0 = new SimpleOptionHandler(0);
      assertFalse(simpleOptionHandler0.getInitLocal());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SimpleOptionHandler simpleOptionHandler0 = new SimpleOptionHandler(78, false, false, false, false);
      assertFalse(simpleOptionHandler0.getAcceptLocal());
  }
}
