/*
 * This file was automatically generated by EvoSuite
 * Thu Oct 19 22:01:17 GMT 2023
 */

package org.apache.commons.net.util;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.EventListener;
import java.util.Iterator;
import org.apache.commons.net.util.ListenerList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ListenerList_ESTest extends ListenerList_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ListenerList listenerList0 = new ListenerList();
      listenerList0.addListener((EventListener) null);
      int int0 = listenerList0.getListenerCount();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ListenerList listenerList0 = new ListenerList();
      listenerList0.removeListener((EventListener) null);
      assertEquals(0, listenerList0.getListenerCount());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ListenerList listenerList0 = new ListenerList();
      int int0 = listenerList0.getListenerCount();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ListenerList listenerList0 = new ListenerList();
      Iterator<EventListener> iterator0 = listenerList0.iterator();
      assertNotNull(iterator0);
  }
}
