/*
 * This file was automatically generated by EvoSuite
 * Thu Oct 19 23:09:03 GMT 2023
 */

package org.apache.commons.net.pop3;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.Reader;
import org.apache.commons.net.pop3.POP3Client;
import org.apache.commons.net.pop3.POP3MessageInfo;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class POP3Client_ESTest extends POP3Client_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      POP3Client pOP3Client0 = new POP3Client();
      Reader reader0 = pOP3Client0.retrieveMessageTop((-2917), 0);
      assertNull(reader0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      POP3Client pOP3Client0 = new POP3Client();
      pOP3Client0.setState(1);
      // Undeclared exception!
      try { 
        pOP3Client0.retrieveMessage(110);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Socket is not connected
         //
         verifyException("org.apache.commons.net.pop3.POP3", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      POP3Client pOP3Client0 = new POP3Client();
      pOP3Client0.setState(0);
      // Undeclared exception!
      try { 
        pOP3Client0.login("\r\n", "H", "\r\n");
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Socket is not connected
         //
         verifyException("org.apache.commons.net.pop3.POP3", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      POP3Client pOP3Client0 = new POP3Client();
      pOP3Client0.setState(2);
      boolean boolean0 = pOP3Client0.login((String) null, "", (String) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      POP3Client pOP3Client0 = new POP3Client();
      pOP3Client0.setState(2);
      boolean boolean0 = pOP3Client0.login("", "");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      POP3Client pOP3Client0 = new POP3Client();
      // Undeclared exception!
      try { 
        pOP3Client0.capa();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Socket is not connected
         //
         verifyException("org.apache.commons.net.pop3.POP3", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      POP3Client pOP3Client0 = new POP3Client();
      POP3MessageInfo pOP3MessageInfo0 = pOP3Client0.status();
      assertNull(pOP3MessageInfo0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      POP3Client pOP3Client0 = new POP3Client();
      Reader reader0 = pOP3Client0.retrieveMessageTop((-22), 756);
      assertNull(reader0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      POP3Client pOP3Client0 = new POP3Client();
      Reader reader0 = pOP3Client0.retrieveMessageTop(7, (-22));
      assertNull(reader0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      POP3Client pOP3Client0 = new POP3Client();
      Reader reader0 = pOP3Client0.retrieveMessage(712);
      assertNull(reader0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      POP3Client pOP3Client0 = new POP3Client();
      pOP3Client0.setState(1);
      // Undeclared exception!
      try { 
        pOP3Client0.retrieveMessage(0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Socket is not connected
         //
         verifyException("org.apache.commons.net.pop3.POP3", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      POP3Client pOP3Client0 = new POP3Client();
      boolean boolean0 = pOP3Client0.reset();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      POP3Client pOP3Client0 = new POP3Client();
      boolean boolean0 = pOP3Client0.noop();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      POP3Client pOP3Client0 = new POP3Client();
      // Undeclared exception!
      try { 
        pOP3Client0.logout();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Socket is not connected
         //
         verifyException("org.apache.commons.net.pop3.POP3", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      POP3Client pOP3Client0 = new POP3Client();
      boolean boolean0 = pOP3Client0.login("", "G8Ek^K:7 %n65nn$x$Q", "*k5Zg`");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      POP3Client pOP3Client0 = new POP3Client();
      boolean boolean0 = pOP3Client0.login("[BevF=kJN", "v");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      POP3Client pOP3Client0 = new POP3Client();
      pOP3Client0.setState(0);
      // Undeclared exception!
      try { 
        pOP3Client0.login((String) null, "");
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Socket is not connected
         //
         verifyException("org.apache.commons.net.pop3.POP3", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      POP3Client pOP3Client0 = new POP3Client();
      POP3MessageInfo[] pOP3MessageInfoArray0 = pOP3Client0.listUniqueIdentifiers();
      assertNull(pOP3MessageInfoArray0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      POP3Client pOP3Client0 = new POP3Client();
      POP3MessageInfo pOP3MessageInfo0 = pOP3Client0.listUniqueIdentifier((-1237));
      assertNull(pOP3MessageInfo0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      POP3Client pOP3Client0 = new POP3Client();
      POP3MessageInfo[] pOP3MessageInfoArray0 = pOP3Client0.listMessages();
      assertNull(pOP3MessageInfoArray0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      POP3Client pOP3Client0 = new POP3Client();
      POP3MessageInfo pOP3MessageInfo0 = pOP3Client0.listMessage(13);
      assertNull(pOP3MessageInfo0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      POP3Client pOP3Client0 = new POP3Client();
      boolean boolean0 = pOP3Client0.deleteMessage((-294));
      assertFalse(boolean0);
  }
}
