/*
 * This file was automatically generated by EvoSuite
 * Thu Oct 19 22:35:10 GMT 2023
 */

package org.apache.commons.net.examples.mail;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.FileNotFoundException;
import java.io.IOException;
import org.apache.commons.net.examples.mail.IMAPExportMbox;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.System;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class IMAPExportMbox_ESTest extends IMAPExportMbox_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      String[] stringArray0 = new String[9];
      stringArray0[0] = "wf0bo:oLOCz5).b5";
      stringArray0[1] = "~%.";
      stringArray0[2] = "+-?VG+VJ4";
      // Undeclared exception!
      try { 
        IMAPExportMbox.main(stringArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid folderPath: 'null'
         //
         verifyException("org.apache.commons.net.examples.mail.IMAPExportMbox", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      String[] stringArray0 = new String[9];
      stringArray0[0] = "";
      stringArray0[1] = "U4g74P$Lpk??cI};~)q";
      stringArray0[2] = "";
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("U4g74P$Lpk??cI};~)q");
      FileSystemHandling.appendStringToFile(evoSuiteFile0, "U4g74P$Lpk??cI};~)q");
      try { 
        IMAPExportMbox.main(stringArray0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // mailbox file: U4g74P$Lpk??cI};~)q already exists and is non-empty!
         //
         verifyException("org.apache.commons.net.examples.mail.IMAPExportMbox", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      String[] stringArray0 = new String[7];
      stringArray0[0] = "lI/!W";
      stringArray0[1] = "";
      stringArray0[2] = "8 mi,`rQD>Ik>e.MWT";
      try { 
        IMAPExportMbox.main(stringArray0);
        fail("Expecting exception: FileNotFoundException");
      
      } catch(FileNotFoundException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockFileOutputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      String[] stringArray0 = new String[6];
      stringArray0[0] = "";
      stringArray0[1] = "-?VG+VJ4";
      stringArray0[2] = "^cB&bBqGu~m";
      // Undeclared exception!
      try { 
        IMAPExportMbox.main(stringArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid folderPath: ''
         //
         verifyException("org.apache.commons.net.examples.mail.IMAPExportMbox", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      String[] stringArray0 = new String[3];
      stringArray0[0] = "imaps";
      stringArray0[1] = "+f'F>ZzZ*!.]{;3";
      stringArray0[2] = "org.apache.commons.net.imap.IMAPClient";
      // Undeclared exception!
      try { 
        IMAPExportMbox.main(stringArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Missing userInfo details
         //
         verifyException("org.apache.commons.net.examples.mail.IMAPUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      String[] stringArray0 = new String[7];
      stringArray0[0] = "lI/!W";
      // Undeclared exception!
      try { 
        IMAPExportMbox.main(stringArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      String[] stringArray0 = new String[3];
      stringArray0[0] = "-CRLF";
      stringArray0[1] = "";
      // Undeclared exception!
      try { 
        IMAPExportMbox.main(stringArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      String[] stringArray0 = new String[9];
      stringArray0[0] = "-%/!#`B#FSL?.J$:/";
      // Undeclared exception!
      try { 
        IMAPExportMbox.main(stringArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Malformed escape pair at index 1: -%/!#`B#FSL?.J$:/
         //
         verifyException("java.net.URI", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      String[] stringArray0 = new String[2];
      stringArray0[0] = "imap://\u0000/";
      // Undeclared exception!
      try { 
        IMAPExportMbox.main(stringArray0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // No match found
         //
         verifyException("java.util.regex.Matcher", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      String[] stringArray0 = new String[6];
      stringArray0[0] = "-X";
      // Undeclared exception!
      try { 
        IMAPExportMbox.main(stringArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      String[] stringArray0 = new String[4];
      stringArray0[0] = "-.";
      // Undeclared exception!
      try { 
        IMAPExportMbox.main(stringArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      String[] stringArray0 = new String[9];
      stringArray0[0] = "-R";
      // Undeclared exception!
      try { 
        IMAPExportMbox.main(stringArray0);
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // null
         //
         verifyException("java.lang.Integer", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      String[] stringArray0 = new String[5];
      stringArray0[0] = "-r";
      // Undeclared exception!
      try { 
        IMAPExportMbox.main(stringArray0);
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // null
         //
         verifyException("java.lang.Integer", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      String[] stringArray0 = new String[7];
      stringArray0[0] = "-c";
      // Undeclared exception!
      try { 
        IMAPExportMbox.main(stringArray0);
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // null
         //
         verifyException("java.lang.Integer", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      String[] stringArray0 = new String[0];
      // Undeclared exception!
      try { 
        IMAPExportMbox.main(stringArray0);
        fail("Expecting exception: System.SystemExitException");
      
      } catch(System.SystemExitException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.System", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      IMAPExportMbox iMAPExportMbox0 = new IMAPExportMbox();
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      String[] stringArray0 = new String[5];
      stringArray0[0] = "-LF";
      stringArray0[1] = "@0/";
      stringArray0[2] = "u!P#;8j";
      stringArray0[3] = "Connection closed without indication.";
      // Undeclared exception!
      try { 
        IMAPExportMbox.main(stringArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Missing userInfo details
         //
         verifyException("org.apache.commons.net.examples.mail.IMAPUtils", e);
      }
  }
}
