/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 14 17:41:46 GMT 2023
 */

package org.apache.commons.net.examples.mail;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.net.examples.mail.SMTPMail;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.System;
import org.evosuite.runtime.util.SystemInUtil;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SMTPMail_ESTest extends SMTPMail_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try { 
        SMTPMail.main((String[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.examples.mail.SMTPMail", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String[] stringArray0 = new String[3];
      SystemInUtil.addInputLine("4rFR.S");
      SystemInUtil.addInputLine("4rFR.S");
      SystemInUtil.addInputLine("");
      SystemInUtil.addInputLine("");
      SystemInUtil.addInputLine("");
      // Undeclared exception!
      try { 
        SMTPMail.main(stringArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // hostname can't be null
         //
         verifyException("org.evosuite.runtime.mock.java.net.MockInetSocketAddress", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      String[] stringArray0 = new String[2];
      SystemInUtil.addInputLine(")@>g(##3 Yc3?E[X[Q");
      SystemInUtil.addInputLine(")@>g(##3 Yc3?E[X[Q");
      SystemInUtil.addInputLine(")@>g(##3 Yc3?E[X[Q");
      SystemInUtil.addInputLine(")@>g(##3 Yc3?E[X[Q");
      // Undeclared exception!
      try { 
        SMTPMail.main(stringArray0);
        fail("Expecting exception: System.SystemExitException");
      
      } catch(System.SystemExitException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.System", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      String[] stringArray0 = new String[0];
      // Undeclared exception!
      try { 
        SMTPMail.main(stringArray0);
        fail("Expecting exception: System.SystemExitException");
      
      } catch(System.SystemExitException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.System", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      SMTPMail sMTPMail0 = new SMTPMail();
  }
}
