/*
 * This file was automatically generated by EvoSuite
 * Thu Oct 19 23:15:54 GMT 2023
 */

package org.apache.commons.net.smtp;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.net.ProtocolCommandListener;
import org.apache.commons.net.smtp.SMTP;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SMTP_ESTest extends SMTP_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      SMTP sMTP0 = new SMTP("r+");
      sMTP0.getCommandSupport();
      assertEquals(25, sMTP0.getDefaultPort());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      SMTP sMTP0 = new SMTP("PRAlWD[c d$eQX@]");
      // Undeclared exception!
      try { 
        sMTP0.sendCommand((-5481), "y0?");
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -5481
         //
         verifyException("org.apache.commons.net.smtp.SMTPCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      SMTP sMTP0 = new SMTP((String) null);
      // Undeclared exception!
      try { 
        sMTP0.sendCommand(2680);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 2680
         //
         verifyException("org.apache.commons.net.smtp.SMTPCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      SMTP sMTP0 = new SMTP("Connection closed without indication.");
      // Undeclared exception!
      try { 
        sMTP0.getReply();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.smtp.SMTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      SMTP sMTP0 = new SMTP("Connection closed without indication.");
      // Undeclared exception!
      try { 
        sMTP0.sendCommand(8);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.smtp.SMTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      SMTP sMTP0 = new SMTP("Rnzo$y^Wf?D#Q2?go");
      // Undeclared exception!
      try { 
        sMTP0.sendCommand("", "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.smtp.SMTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      SMTP sMTP0 = new SMTP("e]}GS+gt,JA'eK8r");
      // Undeclared exception!
      try { 
        sMTP0.sendCommand(0, "HELP");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.smtp.SMTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      SMTP sMTP0 = new SMTP();
      String string0 = sMTP0.getReplyString();
      assertNull(string0);
      assertEquals(25, sMTP0.getDefaultPort());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      SMTP sMTP0 = new SMTP("1CnP \"`7x");
      // Undeclared exception!
      try { 
        sMTP0.vrfy("1CnP \"`7x");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.smtp.SMTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      SMTP sMTP0 = new SMTP();
      // Undeclared exception!
      try { 
        sMTP0.noop();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.smtp.SMTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      SMTP sMTP0 = new SMTP("");
      // Undeclared exception!
      try { 
        sMTP0.saml(".d|x;?X`:f!");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.smtp.SMTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      SMTP sMTP0 = new SMTP();
      // Undeclared exception!
      try { 
        sMTP0.turn();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.smtp.SMTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      SMTP sMTP0 = new SMTP();
      ProtocolCommandListener protocolCommandListener0 = mock(ProtocolCommandListener.class, new ViolatedAssumptionAnswer());
      sMTP0.removeProtocolCommandistener(protocolCommandListener0);
      assertEquals(25, sMTP0.getDefaultPort());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      SMTP sMTP0 = new SMTP();
      sMTP0.disconnect();
      assertEquals(25, sMTP0.getDefaultPort());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      SMTP sMTP0 = new SMTP();
      // Undeclared exception!
      try { 
        sMTP0.send("org.apache.commons.net.DefaultSocketFactory");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.smtp.SMTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      SMTP sMTP0 = new SMTP("");
      // Undeclared exception!
      try { 
        sMTP0.helo("");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.smtp.SMTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      SMTP sMTP0 = new SMTP();
      int int0 = sMTP0.getReplyCode();
      assertEquals(25, sMTP0.getDefaultPort());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      SMTP sMTP0 = new SMTP();
      // Undeclared exception!
      try { 
        sMTP0.rcpt("\u0000#g");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.smtp.SMTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      SMTP sMTP0 = new SMTP("ncy%Prr3jM");
      // Undeclared exception!
      try { 
        sMTP0._connectAction_();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.SocketClient", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      SMTP sMTP0 = new SMTP("aBzCJFfw6@FL-Jxk5");
      // Undeclared exception!
      try { 
        sMTP0.data();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.smtp.SMTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      SMTP sMTP0 = new SMTP("M[0&R5SwY_Zo3y9*");
      // Undeclared exception!
      try { 
        sMTP0.sendCommand("ISO-8859-1");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.smtp.SMTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      SMTP sMTP0 = new SMTP("HELO");
      // Undeclared exception!
      try { 
        sMTP0.help();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.smtp.SMTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      SMTP sMTP0 = new SMTP();
      // Undeclared exception!
      try { 
        sMTP0.help("");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.smtp.SMTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      SMTP sMTP0 = new SMTP();
      sMTP0.getReplyStrings();
      assertEquals(25, sMTP0.getDefaultPort());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      SMTP sMTP0 = new SMTP("q)N?h*MMa`RBNi\u0002");
      // Undeclared exception!
      try { 
        sMTP0.quit();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.smtp.SMTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      SMTP sMTP0 = new SMTP("MC^th}5_UPz*<H5?");
      // Undeclared exception!
      try { 
        sMTP0.expn("RCPT TO:");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.smtp.SMTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      SMTP sMTP0 = new SMTP();
      // Undeclared exception!
      try { 
        sMTP0.mail((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.smtp.SMTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      SMTP sMTP0 = new SMTP();
      // Undeclared exception!
      try { 
        sMTP0.soml("744~b&");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.smtp.SMTP", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      SMTP sMTP0 = new SMTP();
      // Undeclared exception!
      try { 
        sMTP0.rset();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.smtp.SMTP", e);
      }
  }
}
