/*
 * This file was automatically generated by EvoSuite
 * Thu Oct 19 22:59:29 GMT 2023
 */

package org.apache.commons.net.io;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.net.io.CopyStreamAdapter;
import org.apache.commons.net.io.CopyStreamEvent;
import org.apache.commons.net.io.CopyStreamListener;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CopyStreamAdapter_ESTest extends CopyStreamAdapter_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      CopyStreamAdapter copyStreamAdapter0 = new CopyStreamAdapter();
      copyStreamAdapter0.bytesTransferred((-3962L), 0, (long) (-1776));
      copyStreamAdapter0.bytesTransferred(1L, (-1776), (-1427L));
      copyStreamAdapter0.addCopyStreamListener((CopyStreamListener) null);
      CopyStreamEvent copyStreamEvent0 = mock(CopyStreamEvent.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        copyStreamAdapter0.bytesTransferred(copyStreamEvent0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.io.CopyStreamAdapter", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      CopyStreamAdapter copyStreamAdapter0 = new CopyStreamAdapter();
      long long0 = 0L;
      copyStreamAdapter0.bytesTransferred(0L, (-750), 0L);
      CopyStreamAdapter copyStreamAdapter1 = new CopyStreamAdapter();
      copyStreamAdapter0.removeCopyStreamListener(copyStreamAdapter1);
      copyStreamAdapter0.bytesTransferred((-2976L), 0, 1L);
      CopyStreamListener copyStreamListener0 = null;
      copyStreamAdapter1.removeCopyStreamListener(copyStreamAdapter0);
      long long1 = 0L;
      copyStreamAdapter0.bytesTransferred(1L, 2380, 0L);
      copyStreamAdapter0.removeCopyStreamListener((CopyStreamListener) null);
      copyStreamAdapter0.bytesTransferred((-3743L), 0, 0L);
      CopyStreamEvent copyStreamEvent0 = mock(CopyStreamEvent.class, new ViolatedAssumptionAnswer());
      CopyStreamEvent copyStreamEvent1 = mock(CopyStreamEvent.class, new ViolatedAssumptionAnswer());
      copyStreamAdapter1.bytesTransferred(copyStreamEvent1);
      copyStreamAdapter1.bytesTransferred(copyStreamEvent0);
      CopyStreamEvent copyStreamEvent2 = mock(CopyStreamEvent.class, new ViolatedAssumptionAnswer());
      copyStreamAdapter0.bytesTransferred(copyStreamEvent2);
      copyStreamAdapter0.addCopyStreamListener((CopyStreamListener) null);
      copyStreamAdapter0.addCopyStreamListener((CopyStreamListener) null);
      copyStreamAdapter1.removeCopyStreamListener(copyStreamAdapter0);
      copyStreamAdapter0.addCopyStreamListener(copyStreamAdapter1);
      // Undeclared exception!
      try { 
        copyStreamAdapter0.bytesTransferred((-1L), (-1), (long) (-1));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.io.CopyStreamAdapter", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      CopyStreamAdapter copyStreamAdapter0 = new CopyStreamAdapter();
      CopyStreamListener copyStreamListener0 = null;
      CopyStreamEvent copyStreamEvent0 = mock(CopyStreamEvent.class, new ViolatedAssumptionAnswer());
      copyStreamAdapter0.bytesTransferred(copyStreamEvent0);
      copyStreamAdapter0.addCopyStreamListener((CopyStreamListener) null);
      int int0 = 1729;
      // Undeclared exception!
      try { 
        copyStreamAdapter0.bytesTransferred(0L, 1729, 0L);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.io.CopyStreamAdapter", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      CopyStreamAdapter copyStreamAdapter0 = new CopyStreamAdapter();
      CopyStreamListener copyStreamListener0 = null;
      CopyStreamAdapter copyStreamAdapter1 = new CopyStreamAdapter();
      copyStreamAdapter0.addCopyStreamListener(copyStreamAdapter1);
      copyStreamAdapter0.addCopyStreamListener((CopyStreamListener) null);
      long long0 = (-1L);
      CopyStreamEvent copyStreamEvent0 = mock(CopyStreamEvent.class, new ViolatedAssumptionAnswer());
      CopyStreamEvent copyStreamEvent1 = mock(CopyStreamEvent.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        copyStreamAdapter0.bytesTransferred(copyStreamEvent1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.io.CopyStreamAdapter", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      CopyStreamAdapter copyStreamAdapter0 = new CopyStreamAdapter();
      CopyStreamEvent copyStreamEvent0 = mock(CopyStreamEvent.class, new ViolatedAssumptionAnswer());
      copyStreamAdapter0.bytesTransferred(copyStreamEvent0);
      CopyStreamAdapter copyStreamAdapter1 = new CopyStreamAdapter();
      CopyStreamEvent copyStreamEvent1 = mock(CopyStreamEvent.class, new ViolatedAssumptionAnswer());
      copyStreamAdapter1.bytesTransferred(copyStreamEvent1);
      copyStreamAdapter0.removeCopyStreamListener(copyStreamAdapter1);
      copyStreamAdapter1.removeCopyStreamListener(copyStreamAdapter0);
      CopyStreamEvent copyStreamEvent2 = mock(CopyStreamEvent.class, new ViolatedAssumptionAnswer());
      copyStreamAdapter1.removeCopyStreamListener(copyStreamAdapter0);
      copyStreamAdapter0.bytesTransferred(copyStreamEvent2);
      copyStreamAdapter0.removeCopyStreamListener(copyStreamAdapter1);
      copyStreamAdapter0.bytesTransferred(0L, (-1067), (long) 581);
      copyStreamAdapter0.bytesTransferred(0L, 581, 0L);
      copyStreamAdapter0.removeCopyStreamListener(copyStreamAdapter1);
      copyStreamAdapter0.bytesTransferred(0L, 0, (-1L));
      CopyStreamEvent copyStreamEvent3 = mock(CopyStreamEvent.class, new ViolatedAssumptionAnswer());
      copyStreamAdapter1.removeCopyStreamListener(copyStreamAdapter0);
      copyStreamAdapter0.addCopyStreamListener(copyStreamAdapter1);
      copyStreamAdapter0.bytesTransferred((-1L), 0, (-1625L));
      copyStreamAdapter1.bytesTransferred(copyStreamEvent3);
      copyStreamAdapter0.bytesTransferred((-890L), 72, (long) 581);
      copyStreamAdapter1.bytesTransferred((-319L), (-382), (-1352L));
      copyStreamAdapter0.addCopyStreamListener(copyStreamAdapter1);
      assertFalse(copyStreamAdapter0.equals((Object)copyStreamAdapter1));
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      CopyStreamAdapter copyStreamAdapter0 = new CopyStreamAdapter();
      CopyStreamAdapter copyStreamAdapter1 = new CopyStreamAdapter();
      CopyStreamEvent copyStreamEvent0 = mock(CopyStreamEvent.class, new ViolatedAssumptionAnswer());
      copyStreamAdapter0.bytesTransferred(copyStreamEvent0);
      copyStreamAdapter0.removeCopyStreamListener(copyStreamAdapter1);
      CopyStreamEvent copyStreamEvent1 = mock(CopyStreamEvent.class, new ViolatedAssumptionAnswer());
      copyStreamAdapter0.bytesTransferred(copyStreamEvent1);
      CopyStreamEvent copyStreamEvent2 = mock(CopyStreamEvent.class, new ViolatedAssumptionAnswer());
      copyStreamAdapter0.bytesTransferred(copyStreamEvent2);
      copyStreamAdapter1.bytesTransferred(1L, 1, 206L);
      assertFalse(copyStreamAdapter1.equals((Object)copyStreamAdapter0));
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      CopyStreamAdapter copyStreamAdapter0 = new CopyStreamAdapter();
      CopyStreamEvent copyStreamEvent0 = mock(CopyStreamEvent.class, new ViolatedAssumptionAnswer());
      copyStreamAdapter0.bytesTransferred(copyStreamEvent0);
      CopyStreamAdapter copyStreamAdapter1 = new CopyStreamAdapter();
      CopyStreamEvent copyStreamEvent1 = mock(CopyStreamEvent.class, new ViolatedAssumptionAnswer());
      copyStreamAdapter1.bytesTransferred(copyStreamEvent1);
      copyStreamAdapter0.removeCopyStreamListener(copyStreamAdapter1);
      CopyStreamEvent copyStreamEvent2 = mock(CopyStreamEvent.class, new ViolatedAssumptionAnswer());
      copyStreamAdapter0.bytesTransferred(copyStreamEvent2);
      CopyStreamAdapter copyStreamAdapter2 = new CopyStreamAdapter();
      copyStreamAdapter2.addCopyStreamListener(copyStreamAdapter1);
      copyStreamAdapter0.removeCopyStreamListener(copyStreamAdapter2);
      copyStreamAdapter2.bytesTransferred(1L, (-1084), (-1L));
      CopyStreamEvent copyStreamEvent3 = mock(CopyStreamEvent.class, new ViolatedAssumptionAnswer());
      copyStreamAdapter0.bytesTransferred(copyStreamEvent3);
      assertFalse(copyStreamAdapter0.equals((Object)copyStreamAdapter2));
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      CopyStreamAdapter copyStreamAdapter0 = new CopyStreamAdapter();
      CopyStreamAdapter copyStreamAdapter1 = new CopyStreamAdapter();
      CopyStreamEvent copyStreamEvent0 = mock(CopyStreamEvent.class, new ViolatedAssumptionAnswer());
      copyStreamAdapter1.bytesTransferred(copyStreamEvent0);
      copyStreamAdapter0.bytesTransferred(0L, (-2146), 0L);
      copyStreamAdapter1.bytesTransferred(0L, 0, 0L);
      copyStreamAdapter1.addCopyStreamListener(copyStreamAdapter0);
      copyStreamAdapter0.removeCopyStreamListener(copyStreamAdapter1);
      CopyStreamEvent copyStreamEvent1 = mock(CopyStreamEvent.class, new ViolatedAssumptionAnswer());
      copyStreamAdapter0.bytesTransferred(copyStreamEvent1);
      copyStreamAdapter0.bytesTransferred((-364L), (-882), 455L);
      copyStreamAdapter1.removeCopyStreamListener(copyStreamAdapter0);
      copyStreamAdapter1.removeCopyStreamListener(copyStreamAdapter0);
      CopyStreamEvent copyStreamEvent2 = mock(CopyStreamEvent.class, new ViolatedAssumptionAnswer());
      copyStreamAdapter1.bytesTransferred(copyStreamEvent2);
      copyStreamAdapter1.removeCopyStreamListener(copyStreamAdapter0);
      CopyStreamEvent copyStreamEvent3 = mock(CopyStreamEvent.class, new ViolatedAssumptionAnswer());
      copyStreamAdapter0.bytesTransferred(copyStreamEvent3);
      copyStreamAdapter0.addCopyStreamListener(copyStreamAdapter1);
      copyStreamAdapter1.bytesTransferred((-364L), (-882), 1357L);
      copyStreamAdapter0.addCopyStreamListener(copyStreamAdapter1);
      assertFalse(copyStreamAdapter0.equals((Object)copyStreamAdapter1));
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CopyStreamAdapter copyStreamAdapter0 = new CopyStreamAdapter();
      CopyStreamEvent copyStreamEvent0 = mock(CopyStreamEvent.class, new ViolatedAssumptionAnswer());
      copyStreamAdapter0.bytesTransferred(copyStreamEvent0);
      copyStreamAdapter0.bytesTransferred(0L, (-276), (long) (-276));
      CopyStreamAdapter copyStreamAdapter1 = new CopyStreamAdapter();
      copyStreamAdapter0.addCopyStreamListener(copyStreamAdapter1);
      copyStreamAdapter0.removeCopyStreamListener(copyStreamAdapter1);
      copyStreamAdapter0.bytesTransferred((long) (-276), (-1), (-34L));
      copyStreamAdapter0.bytesTransferred(343L, (-1), 0L);
      assertFalse(copyStreamAdapter0.equals((Object)copyStreamAdapter1));
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      CopyStreamAdapter copyStreamAdapter0 = new CopyStreamAdapter();
      CopyStreamAdapter copyStreamAdapter1 = new CopyStreamAdapter();
      copyStreamAdapter0.removeCopyStreamListener(copyStreamAdapter1);
      CopyStreamAdapter copyStreamAdapter2 = new CopyStreamAdapter();
      copyStreamAdapter0.removeCopyStreamListener(copyStreamAdapter2);
      copyStreamAdapter0.addCopyStreamListener(copyStreamAdapter2);
      copyStreamAdapter0.removeCopyStreamListener(copyStreamAdapter2);
      CopyStreamAdapter copyStreamAdapter3 = new CopyStreamAdapter();
      copyStreamAdapter0.removeCopyStreamListener(copyStreamAdapter3);
      copyStreamAdapter3.removeCopyStreamListener(copyStreamAdapter0);
      copyStreamAdapter3.addCopyStreamListener(copyStreamAdapter2);
      CopyStreamEvent copyStreamEvent0 = mock(CopyStreamEvent.class, new ViolatedAssumptionAnswer());
      copyStreamAdapter2.bytesTransferred(copyStreamEvent0);
      copyStreamAdapter0.removeCopyStreamListener(copyStreamAdapter2);
      CopyStreamAdapter copyStreamAdapter4 = new CopyStreamAdapter();
      copyStreamAdapter3.addCopyStreamListener(copyStreamAdapter4);
      copyStreamAdapter3.addCopyStreamListener(copyStreamAdapter1);
      CopyStreamEvent copyStreamEvent1 = mock(CopyStreamEvent.class, new ViolatedAssumptionAnswer());
      copyStreamAdapter4.bytesTransferred(copyStreamEvent1);
      copyStreamAdapter2.removeCopyStreamListener(copyStreamAdapter1);
      copyStreamAdapter4.bytesTransferred((-1L), (-3623), 3317L);
      CopyStreamAdapter copyStreamAdapter5 = new CopyStreamAdapter();
      copyStreamAdapter0.removeCopyStreamListener(copyStreamAdapter5);
      assertFalse(copyStreamAdapter5.equals((Object)copyStreamAdapter0));
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      CopyStreamAdapter copyStreamAdapter0 = new CopyStreamAdapter();
      CopyStreamEvent copyStreamEvent0 = mock(CopyStreamEvent.class, new ViolatedAssumptionAnswer());
      copyStreamAdapter0.bytesTransferred(copyStreamEvent0);
      CopyStreamEvent copyStreamEvent1 = mock(CopyStreamEvent.class, new ViolatedAssumptionAnswer());
      CopyStreamAdapter copyStreamAdapter1 = new CopyStreamAdapter();
      copyStreamAdapter0.removeCopyStreamListener(copyStreamAdapter1);
      copyStreamAdapter0.bytesTransferred(copyStreamEvent1);
      CopyStreamAdapter copyStreamAdapter2 = new CopyStreamAdapter();
      copyStreamAdapter0.removeCopyStreamListener(copyStreamAdapter2);
      CopyStreamEvent copyStreamEvent2 = mock(CopyStreamEvent.class, new ViolatedAssumptionAnswer());
      copyStreamAdapter2.bytesTransferred(copyStreamEvent2);
      copyStreamAdapter0.bytesTransferred((-1L), 0, (-1L));
      copyStreamAdapter0.bytesTransferred((-1L), 0, (-1L));
      CopyStreamEvent copyStreamEvent3 = mock(CopyStreamEvent.class, new ViolatedAssumptionAnswer());
      copyStreamAdapter1.bytesTransferred(copyStreamEvent3);
      CopyStreamEvent copyStreamEvent4 = mock(CopyStreamEvent.class, new ViolatedAssumptionAnswer());
      CopyStreamAdapter copyStreamAdapter3 = new CopyStreamAdapter();
      copyStreamAdapter1.addCopyStreamListener(copyStreamAdapter3);
      copyStreamAdapter2.bytesTransferred(copyStreamEvent4);
      copyStreamAdapter1.removeCopyStreamListener(copyStreamAdapter2);
      copyStreamAdapter0.bytesTransferred(1L, (-136), (-1L));
      copyStreamAdapter3.bytesTransferred(0L, 0, 0L);
      copyStreamAdapter1.addCopyStreamListener(copyStreamAdapter2);
      assertFalse(copyStreamAdapter1.equals((Object)copyStreamAdapter0));
  }
}
