/*
 * This file was automatically generated by EvoSuite
 * Thu Oct 19 23:13:29 GMT 2023
 */

package org.apache.commons.net.ftp.parser;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.net.ftp.FTPFile;
import org.apache.commons.net.ftp.parser.EnterpriseUnixFTPEntryParser;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class EnterpriseUnixFTPEntryParser_ESTest extends EnterpriseUnixFTPEntryParser_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      EnterpriseUnixFTPEntryParser enterpriseUnixFTPEntryParser0 = new EnterpriseUnixFTPEntryParser();
      // Undeclared exception!
      try { 
        enterpriseUnixFTPEntryParser0.parseFTPEntry((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      EnterpriseUnixFTPEntryParser enterpriseUnixFTPEntryParser0 = new EnterpriseUnixFTPEntryParser();
      enterpriseUnixFTPEntryParser0.setRegex("2Ea%", 1886);
      // Undeclared exception!
      try { 
        enterpriseUnixFTPEntryParser0.parseFTPEntry("2Ea%");
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // No group 14
         //
         verifyException("java.util.regex.Matcher", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      EnterpriseUnixFTPEntryParser enterpriseUnixFTPEntryParser0 = new EnterpriseUnixFTPEntryParser();
      FTPFile fTPFile0 = enterpriseUnixFTPEntryParser0.parseFTPEntry("(([-]|[A-Z])([-]|[A-Z])([-]|[A-Z])([-]|[A-Z])([-]|[A-Z])([-]|[A-Z])([-]|[A-Z])([-]|[A-Z])([-]|[A-Z])([-]|[A-Z]))(S*)s*(S+)s*(S*)s*(d*)s*(d*)s*(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)s*((?:[012]d*)|(?:3[01]))s*((dddd)|((?:[01]d)|(?:2[0123])):([012345]d))s(S*)(s*.*)");
      assertNull(fTPFile0);
  }
}
